version: "3"
services:
  distcc:
    container_name: distcc-server-local
    build: .
      # context: .
    environment: 
        # - NETWORK=10.0.0.1/16
        - USER=distccd
        - HOME=/home/distccd
        - JOBS=4
    ports:
        - 3632:3632
    user: distccd
    # user: root
    privileged: true
