version: '2'
services:
  distcc:
    container_name: distcc-server-local
    build:
      context: .
    environment: 
        # - NETWORK=10.0.0.1/16
        - JOBS=12
    ports:
        - 3632:3632
    user: distccd
